/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DataView: typeof import('primevue/dataview')['default']
    DataViewLayoutOptions: typeof import('primevue/dataviewlayoutoptions')['default']
    Divider: typeof import('primevue/divider')['default']
    FormItem: typeof import('./src/components/FormItem/FormItem.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    MainTitle: typeof import('./src/components/MainTitle/MainTitle.vue')['default']
    Message: typeof import('primevue/message')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RenderErrors: typeof import('./src/components/RenderErrors/RenderErrors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    ScrollWrapper: typeof import('./src/components/ScrollWrapper/ScrollWrapper.vue')['default']
    SmallText: typeof import('./src/components/SmallText/SmallText.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    SuspensedComponent: typeof import('./src/components/SuspensedComponent/SuspensedComponent.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
